"""URL safety validation and native link-wrapper handling for image destinations.

Image evidence can carry a retained anchor destination on its own
``attributes.href`` (see ``html_ownership.image()``). Composition must
reproduce that destination as a real, clickable native component -- never as
an ``href`` attribute on the ``<img>`` itself -- without disturbing any other
link/button slot's numbering or target. This module is the one place that
knows what a "safe" URL looks like and how an image acquires or loses a
native anchor owner; ``planner.py`` and ``block_compose.py`` integrate it in
a few lines each rather than growing their own copies of this logic.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Sequence

__all__ = [
    "ImageLinkError",
    "is_safe_link_href",
    "validate_link_href",
    "is_image_link_wrapper",
    "is_generated_image_link_wrapper",
    "collect_component_ids",
    "apply_image_link",
]


class ImageLinkError(ValueError):
    """Raised when an image-link override cannot be safely or unambiguously applied."""


# Browsers strip embedded C0 control characters and spaces (tab/newline/CR
# and friends) before parsing a URL's scheme, which is exactly how
# "\tJaVaScRiPt:alert(1)", "\x00javascript:alert(1)", or
# "\x00 javascript:alert(1)" smuggle a dangerous scheme past a naive prefix
# check. Stripping the same characters first closes that gap.
_CONTROL_WHITESPACE = re.compile(r"[\x00-\x20]")
_SCHEME = re.compile(r"^([a-zA-Z][a-zA-Z0-9+.-]*):")

# Schemes a visitor can safely follow from a composed page.
_SAFE_SCHEMES = frozenset({"http", "https", "mailto", "tel"})
# Schemes that execute code or embed content in the browser's security context.
_UNSAFE_SCHEMES = frozenset({"javascript", "vbscript", "data", "file"})


def is_safe_link_href(href: str) -> bool:
    """Return whether ``href`` is a destination a composed native link may carry.

    Relative paths, query strings, and fragments pass through untouched --
    they have no scheme to check. A scheme must be explicitly allow-listed;
    anything unrecognized is rejected the same as a known-dangerous one, so a
    supported destination is opt-in rather than "not yet on the blocklist".
    """
    if not isinstance(href, str):
        return False
    text = href.strip()
    if not text:
        return False
    collapsed = _CONTROL_WHITESPACE.sub("", text)
    match = _SCHEME.match(collapsed)
    if match is None:
        return True
    scheme = match.group(1).casefold()
    if scheme in _UNSAFE_SCHEMES:
        return False
    return scheme in _SAFE_SCHEMES


def validate_link_href(href: str | None) -> str:
    """Return ``href`` trimmed, or raise ``ImageLinkError`` if it is unsafe.

    A blank value means "clear the link" and is always accepted. The error
    message never echoes the rejected URL: a query string or mailto address
    can carry a token or address that a log or terminal shouldn't repeat.
    """
    text = "" if href is None else str(href).strip()
    if not text:
        return ""
    if not is_safe_link_href(text):
        raise ImageLinkError("unsupported or unsafe link destination")
    return text


def is_image_link_wrapper(component: dict) -> bool:
    """A ``link`` whose only child is a single image: a pure destination wrapper shape.

    This is a *shape* test only -- it says nothing about whether the wrapper
    was authored by a human or generated by ``apply_image_link`` below, so it
    identifies a candidate to reuse (or reject as ambiguous) when wrapping an
    image, and a node whose ``href`` currently represents an image's
    ``image_N_href`` slot value. It must NOT be used to decide ``link_N``
    numbering: a template author can legitimately write a content-free link
    around an image (see ``is_generated_image_link_wrapper`` for the check
    that actually distinguishes "ours" from "authored" for that purpose). A
    link that happens to wrap a single image but also carries real
    visitor-facing ``content`` (a labeled anchor, not a bare wrapper) is
    deliberately excluded: it is existing ownership to leave alone or reject,
    never a slot to reuse silently.
    """
    if not isinstance(component, dict) or component.get("type") != "link":
        return False
    if component.get("content"):
        return False
    children = component.get("components")
    if not isinstance(children, list) or len(children) != 1:
        return False
    child = children[0]
    return isinstance(child, dict) and child.get("type") == "image"


# A class token this module alone writes, and only at the moment it builds a
# wrapper that did not previously exist in the template (see _new_wrapper).
# Never a shape or id an authored template would organically reproduce
# (unlike an id-naming convention, which a human absolutely can and does
# reuse independently -- see the "image derived" id case in the root
# acceptance's authored-owner test) and never added when *adopting* an
# already-existing wrapper (see _ensure_vj_link_class): an authored wrapper
# keeps whatever link_N identity it already had even after its href starts
# being managed through image_N_href, exactly like any other authored
# component apply_overrides updates in place.
_IMAGE_LINK_MARKER_CLASS = "vj-image-link"


def is_generated_image_link_wrapper(component: dict) -> bool:
    """Whether ``component`` is a link ``_new_wrapper`` built from nothing.

    Content shape alone (see ``is_image_link_wrapper``) cannot tell "a
    wrapper this code built" from "a wrapper the template author wrote":
    both can be a content-free ``link`` around a single ``image``, and even
    the wrapper's own id is no help -- a template author can independently
    choose the very same naming convention ``_wrapper_id_base`` would
    generate. Only the dedicated ``_IMAGE_LINK_MARKER_CLASS`` class, stamped
    solely by ``_new_wrapper`` at creation time (never by the reuse path
    that adopts an existing wrapper -- see ``_ensure_vj_link_class``), is
    excluded from ``link_N``/``link_N_href`` numbering; every other
    content-free single-image wrapper -- including an authored one whose
    destination is now also managed via ``image_N_href`` -- still counts as
    an ordinary link slot, on this and every later composition round.
    """
    if not is_image_link_wrapper(component):
        return False
    classes = component.get("classes")
    if not isinstance(classes, list):
        return False
    return any(
        isinstance(entry, dict) and entry.get("name") == _IMAGE_LINK_MARKER_CLASS
        for entry in classes
    )


def collect_component_ids(root: dict) -> set[str]:
    """Every ``attributes.id`` present anywhere in ``root``'s component tree."""
    ids: set[str] = set()
    stack = [root]
    while stack:
        node = stack.pop()
        if not isinstance(node, dict):
            continue
        component_id = (node.get("attributes") or {}).get("id")
        if isinstance(component_id, str) and component_id:
            ids.add(component_id)
        children = node.get("components")
        if isinstance(children, list):
            stack.extend(children)
    return ids


def _wrapper_id_base(image: dict) -> str:
    """A deterministic starting candidate for the wrapper id, derived from the image's own id.

    Deterministic so repeated composition of the same source produces the
    same wrapper id (required for reproducible output); derived from the
    image rather than generated fresh so it reads like every other template
    id already does. ``_unique_wrapper_id`` resolves any collision with an
    id already present elsewhere in the tree.
    """
    attributes = image.get("attributes") or {}
    image_id = attributes.get("id")
    if isinstance(image_id, str) and image_id:
        return f"{image_id}-link"
    digest = hashlib.sha256(
        json.dumps(image, sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()[:10]
    return f"image-link-{digest}"


def _unique_wrapper_id(image: dict, existing_ids: set[str]) -> str:
    """A wrapper id that does not collide with any id already in the tree.

    Deterministic: the same image and the same set of existing ids always
    resolve to the same disambiguated id, so repeated composition of the same
    source is still reproducible byte-for-byte.
    """
    base = _wrapper_id_base(image)
    if base not in existing_ids:
        existing_ids.add(base)
        return base
    suffix = 2
    while f"{base}-{suffix}" in existing_ids:
        suffix += 1
    candidate = f"{base}-{suffix}"
    existing_ids.add(candidate)
    return candidate


def _ensure_vj_link_class(component: dict) -> None:
    """Ensure the required ``vj-link`` class is present, without touching the marker.

    Used only on the *reuse* path in ``apply_image_link``, deliberately never
    adding ``_IMAGE_LINK_MARKER_CLASS``: an existing single-image wrapper
    being adopted may be an authored link with its own pre-existing
    ``link_N`` identity (see the root acceptance's "reusing an authored
    wrapper must not reclassify it" case), and adopting it must not strip
    that identity away on this or any later composition round. Only
    ``_new_wrapper`` -- a wrapper that did not exist in the template at all
    before this call -- gets the marker, baked in at creation.
    """
    classes = component.setdefault("classes", [])
    if not any(isinstance(entry, dict) and entry.get("name") == "vj-link" for entry in classes):
        classes.append({"name": "vj-link", "active": False})


def _new_wrapper(image: dict, href: str, existing_ids: set[str]) -> dict:
    return {
        "type": "link",
        "tagName": "a",
        "classes": [{"name": "vj-link", "active": False}, {"name": _IMAGE_LINK_MARKER_CLASS, "active": False}],
        "attributes": {"id": _unique_wrapper_id(image, existing_ids), "href": href},
        "components": [image],
    }


def _replace_child(parent: dict, old: dict, new: dict) -> bool:
    children = parent.get("components")
    if not isinstance(children, list):
        return False
    for index, child in enumerate(children):
        if child is old:
            children[index] = new
            return True
    return False


def _has_outer_ownership(ancestors: Sequence[dict], direct_wrapper: dict | None) -> bool:
    """Whether some ancestor other than a recognized direct wrapper already owns a destination.

    Covers both a whole-card link/button several levels up and an immediate
    parent that looks like a link/button but doesn't qualify as a reusable
    single-image owner (a button, or a link with other siblings) -- either
    way, an image-link override must not silently repurpose it.
    """
    for ancestor in ancestors:
        if ancestor is direct_wrapper:
            continue
        if ancestor.get("type") in ("link", "button"):
            return True
    return False


def apply_image_link(
    image: dict,
    parent: dict,
    ancestors: Sequence[dict],
    href: str | None,
    existing_ids: set[str],
) -> None:
    """Give ``image`` a native clickable owner for ``href``, or remove one.

    ``parent`` is ``image``'s direct container; ``ancestors`` is the full
    chain from the tree root down to and including ``parent``. ``existing_ids``
    is every ``attributes.id`` already present in the tree (see
    ``collect_component_ids``); a newly assigned wrapper id is added to it in
    place so a second image wrapped in the same call cannot collide with the
    first. Mutates the tree in place:

    - A blank/empty ``href`` clears an existing direct single-image wrapper
      (the image is kept, just unwrapped) and is otherwise a no-op.
    - A safe non-empty ``href`` updates a compatible existing single-image
      wrapper in place, or wraps the image in a new one.
    - Any other link/button already owning the image (a card-level link, or a
      wrapper shared with other content) is ambiguous ownership: a non-empty
      href raises rather than overwriting an unrelated target; a clear is a
      no-op rather than guessing what to undo.
    """
    validated = validate_link_href(href)
    direct_wrapper = (
        parent
        if is_image_link_wrapper(parent) and parent["components"][0] is image
        else None
    )
    ambiguous = _has_outer_ownership(ancestors, direct_wrapper)

    if not validated:
        if direct_wrapper is not None and len(ancestors) >= 2:
            grandparent = ancestors[-2]
            _replace_child(grandparent, direct_wrapper, image)
        return

    if ambiguous:
        raise ImageLinkError(
            "image already has a destination owned by an enclosing link or "
            "button; refusing to overwrite an unrelated target"
        )

    if direct_wrapper is not None:
        attributes = direct_wrapper.setdefault("attributes", {})
        attributes["href"] = validated
        if not attributes.get("id"):
            attributes["id"] = _unique_wrapper_id(image, existing_ids)
        _ensure_vj_link_class(direct_wrapper)
        return

    _replace_child(parent, image, _new_wrapper(image, validated, existing_ids))
